packages: []

catalogs:
  build:
    '@octohash/vite-config': ^0.3.2
    unplugin-vue-router: ^0.16.0
    vite: ^7.1.12
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.3
    taze: ^19.8.1
  frontend:
    '@unhead/vue': ^2.0.19
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.22
    vue-router: ^4.6.3
  i18n:
    vue-i18n: ^11.1.12
  icons:
    '@iconify-json/lucide': ^1.2.70
  lint:
    '@antfu/eslint-config': ^6.0.0
    '@unocss/eslint-config': ^66.5.4
    eslint: ^9.38.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  style:
    '@unocss/preset-web-fonts': ^66.5.4
    '@unocss/reset': ^66.5.4
    unocss: ^66.5.4
  test:
    vitest: ^4.0.1
  tsc:
    typescript: ^5.9.3
    vue-tsc: ^3.1.1
  types:
    '@types/nprogress': ^0.2.3
  utils:
    '@vueuse/core': ^14.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@swc/core'
